adapters/google_oauth_adapter.go, config/config.go, config/config.json, controllers/auth_controller.go, controllers/auth_controller_test.go, controllers/member_controller.go, controllers/site_controller.go, controllers/site_controller_test.go, domain/auth/auth_service.go, domain/errors.go, domain/member/member_entity.go, domain/member/member_repository.go, domain/member/member_service.go, domain/site/site_entity.go, dtos/auth_dto.go, dtos/member_dto.go, dtos/site_dto.go, testdata/db_fixtures/site_settings.yml
https://github.com/bettercode-oss/better-ADMIN/issues/62
=> 구글 Workspace 로그인 지원

controllers/member_controller.go, controllers/member_controller_test.go, domain/member/member_entity.go, dtos/member_dto.go
=> #8 멤버가 동명이인을 고려하여 이름 옆에 식별할 수 있는 id 나 이메일을 함께 보여 준다.

adapters/web_socket_adapter.go, controllers/access_control_controller.go, controllers/fixture_test.go, controllers/member_controller.go, controllers/member_controller_test.go, controllers/organization_controller.go, controllers/site_controller.go, controllers/web_hook_controller.go, controllers/web_hook_controller_test.go, domain/pre_defined_permissions.go, domain/webhook/web_hook_entity.go, domain/webhook/web_hook_service.go, domain/webhook/webhook_repository.go, dtos/web_hook_dtos.go, go.mod, go.sum, main.go, security/jwt.go, testdata/db_fixtures/web_hook_messages.yml, testdata/db_fixtures/web_hooks.yml
=> #6 알림 기능 지원

controllers/member_controller.go, controllers/member_controller_test.go, domain/member/member_repository.go, domain/member/member_service.go, dtos/member_dto.go, testdata/db_fixtures/members.yml
=> #14 신청한 멤버를 승인 거절하는 API를 만든다.

main.go
=> #11 Echo 미들웨어 순서 변경하기

go.mod, go.sum, security/jwt.go
=> #16 JWT 토큰 생성하는 라이브러리 보안 이슈로 인한 버전 업데이트

main.go
=> #22 MySQL Replica Connection Pool 지원

README.md, db_schema.go, main.go
=> #21 JwtSecret 을 환경 변수로 설정 가능하도록 지원

controllers/access_control_controller_test.go, controllers/member_controller_test.go, controllers/organization_controller_test.go, controllers/site_controller_test.go, controllers/web_hook_controller_test.go, db_schema.go, domain/member/member_entity.go, domain/member/member_repository.go, domain/member/member_service.go, domain/organization/organization_entity.go, domain/organization/organization_repository.go, domain/organization/organization_service.go, domain/rbac/rbac_entity.go, domain/rbac/rbac_repository.go, domain/rbac/rbac_service.go, domain/site/site_entity.go, domain/site/site_service.go, domain/webhook/web_hook_entity.go, domain/webhook/web_hook_service.go, domain/webhook/webhook_repository.go, main.go, testdata/db_fixtures/organizations.yml, testdata/db_fixtures/permissions.yml, testdata/db_fixtures/roles.yml, testdata/db_fixtures/site_settings.yml, testdata/db_fixtures/web_hooks.yml
=> #27 엔티티에 CreatedBy, UpdatedBy 추가하기

.gitignore, controllers/auth_controller.go, controllers/member_controller.go, controllers/member_controller_test.go, domain/auth/auth_service.go, domain/member/member_entity.go, domain/member/member_service.go, dtos/member_dto.go, testdata/db_fixtures/members.yml
=> #28 사용자 로그인 시 accessTime 남기기

controllers/fixture_test.go, controllers/member_access_log_controller.go, controllers/member_access_log_controller_test.go, db_schema.go, domain/errors.go, domain/logging/member_access_log_entity.go, domain/logging/member_access_log_repository.go, domain/logging/member_access_log_service.go, domain/pre_defined_permissions.go, dtos/member_access_log_dtos.go, main.go, testdata/db_fixtures/member_access_logs.yml
=> #34 사용자 접근 로그 API 구현

adapters/dooray_adapter.go, adapters/google_oauth_adapter.go, adapters/web_socket_adapter.go, controllers/access_control_controller.go, controllers/auth_controller.go, controllers/member_access_log_controller.go, controllers/member_controller.go, controllers/menu_controller.go, controllers/organization_controller.go, controllers/site_controller.go, controllers/web_hook_controller.go, domain/auth/auth_service.go, domain/errors.go, domain/logging/member_access_log_repository.go, domain/member/member_entity.go, domain/member/member_repository.go, domain/menu/menu_repository.go, domain/organization/organization_repository.go, domain/rbac/rbac_repository.go, domain/site/site_repository.go, domain/webhook/webhook_repository.go, dtos/member_dto.go, dtos/site_dto.go, go.mod, go.sum, helpers/context_helper.go, main.go, middlewares/error_handler.go, middlewares/gorm_db.go, security/jwt.go
=> #26 서버 오류 발생 시 자동으로 에러 메시지와 stack trace 로그 남기기

controllers/member_access_log_controller.go, controllers/member_access_log_controller_test.go, domain/logging/member_access_log_entity.go, dtos/member_access_log_dtos.go, testdata/db_fixtures/member_access_logs.yml
=> #38 멤버 접근 로그에 HTTP 응답 StatusCode를 추가한다

controllers/member_access_log_controller_test.go, domain/logging/member_access_log_entity.go, dtos/member_access_log_dtos.go, dtos/member_access_log_dtos_test.go, go.mod, go.sum
=> #40 멤버 접근 로그 기록 시 User Agent 를 해석해서 저장 한다

controllers/site_controller.go, controllers/site_controller_test.go, domain/site/entity/site_entity.go, dtos/site_dto.go, services/site_service.go, testdata/db_fixtures/site_settings.yml
=> #52 App Version API를 구현한다.

main.go
=> #56 runtime 오류 시에도 StackTrace 로그 남기기

controllers/access_control_controller.go, controllers/access_control_controller_test.go, dtos/access_control_dtos.go, services/rbac_service.go, testdata/db_fixtures/permissions.yml
=> #58 권한 상세 조회 API 구현하기

controllers/access_control_controller.go, controllers/access_control_controller_test.go, domain/rbac/repository/rbac_repository.go
=> #60 권한 목록 조회 시 필터 조건(이름)을 추가한다.

controllers/access_control_controller.go, controllers/access_control_controller_test.go, dtos/access_control_dtos.go, services/rbac_service.go, testdata/db_fixtures/roles.yml
=> #62 역할 상세 조회 API 구현

controllers/access_control_controller.go, controllers/access_control_controller_test.go, domain/rbac/repository/rbac_repository.go
=> #64 역할 목록 조회 시 필터 조건(이름)을 추가한다.

app/middlewares.go
=> #68 CORS Options Request 캐싱하기

http/rest/auth_controller.go, security/jwt.go, site/domain/site_entity.go
=> #87 Front-end 인증 방식 변경에 따른 API 수정

app/app.go
=> #89 Liveness Probe를 위한 health API 제공하기
